- App/App.csproj
- App/MainWindow.xaml
- App/MainWindow.xaml.cs
- Console/Mirror/MirrorCommand.cs
- Console/Mirror/MirrorOptions.cs
- LibDmd/Input/IFrameSource.cs
- LibDmd/Input/TPAGrabber/TPAGrabber.cs
- LibDmd/LibDmd.csproj
- LibDmd/Processor/AbstractProcessor.cs
- LibDmd/Processor/GridProcessor.cs
- LibDmd/Processor/MonochromeProcessor.cs
- LibDmd/Processor/ShadeProcessor.cs
- LibDmd/Processor/TransformationProcessor.cs
- LibDmd/RenderGraph.cs
- README.md
- Credits go 100% to NoEx for his excellent grabber. Cheers!
- Additionally it's now possible to specify at which luminosity each shade gets rendered on RGB displays.
> Add support for The Pinball Arcade

- LibDmd/Input/TPAGrabber/TPAGrabber.cs
Just messing about with the code to see how it all worked, tried something out and with some very rough profiling it appears to give a fairly decent speed gain.
> Change to use WritePixels (appears to give good performance boost)

- ProPinballBridge/ProPinballBridge.cpp
- ProPinballBridge/ProPinballBridge.h
Loop when waiting for messages and check for the end message, which means we should terminate.
> Send slave ready message to the master on start up.

- LibDmd/Input/TPAGrabber/TPAGrabber.cs
- LibDmd/Output/Virtual/VirtualDmdControl.xaml.cs
better, brighter representation closer to Pinball Arcade default Virtual
DMD
> Improve rendering of VirtualDMD

- LibDmd/Converter/Colorize/Animation.cs
- LibDmd/Converter/Colorize/Coloring.cs
- LibDmd/Input/PinMame/VpmGray2Source.cs
- LibDmd/Input/PinMame/VpmGray4Source.cs
Remove input duplication check that prevents animation enhancements from running
Use frame delay on enhancements correctly
Support 128x16 masks (TMNT)
Closes #108.
> VNI animation timing improvements.

- Console/Common/BaseCommand.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/RenderGraph.cs
New branch for code from #127 (supersedes that request)
> fix close/reopen problems (issue 123)

- Console/DmdExt.cs
- LibDmd/Common/CultureUtil.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/LibDmd.csproj
- LibDmd/Output/Virtual/AlphaNumeric/VirtualAlphanumericDestination.cs
Sorry, picked wrong branch to put the pull request into last time. FYI this window close fix is for the additional settings window, I seen you did the other one, and just applied your same fix to the other window.
> Culture fix and window close fix

- LibDmd/Output/PinDmd1/PinDmd1.cs
- LibDmd/Output/PinDmd2/PinDmd2.cs
- LibDmd/Output/PinDmd3/PinDmd3.cs
> Fix for issue #169

- LibDmd/Output/Pixelcade/Pixelcade.cs
pixelcade serial port tweaks, now can connect and read pixelcade firmware strings, crashing though when writing the test image to pixelcade
> pixelcade serial port fixes

- LibDmd/Input/PinballFX/PinballFX3MemoryGrabber.cs
> Fix memory positions for FX3's Halloween release. Fixes #195.

- LibDmd/Common/VirtualDmd.xaml
- LibDmd/Common/VirtualDmd.xaml.cs
- LibDmd/DmdDevice/Configuration.cs
- LibDmd/DmdDevice/DmdDevice.cs
This adds a context menu that allows saving the DMD position to the `DmdDevice.ini`.
This PR closes #193.
> Add context menu for easier position saving

- LibDmd/Common/FrameUtil.cs
- LibDmd/Converter/Colorize/Animation.cs
- LibDmd/Converter/Colorize/AnimationFrame.cs
- LibDmd/Converter/Colorize/Mapping.cs
- LibDmd/Converter/Colorize/SwitchMode.cs
- LibDmd/Converter/Colorize/VniAnimation.cs
- LibDmd/Converter/Colorize/VniAnimationFrame.cs
- LibDmd/Converter/Colorize/VniAnimationPlane.cs
- LibDmd/Converter/Gray2Colorizer.cs
- LibDmd/Converter/Gray4Colorizer.cs
This adds support for the new Layered Color Mask mode as seen in White Water. 
Thanks to Lucky1 for sharing the algorithm.
> Layered color mask support

- PinMameDevice/DmdDevice.cs
Extend the dmddevice.dll API to support having multiple output (for example PinMame + FlexDMD)
Solve  Issue #271 with the corresponding branch of FlexDMD
> Add support for multiple outputs

- Console/Common/BaseOptions.cs
- LibDmd/DmdDevice/Configuration.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/DmdDevice/IConfiguration.cs
- LibDmd/Output/FileOutput/VideoOutput.cs
- LibDmd/Output/IFixedSizeDestination.cs
- LibDmd/Output/Pin2Dmd/Pin2Dmd.cs
- LibDmd/Output/Pin2Dmd/Pin2DmdHd.cs
- LibDmd/Output/Pin2Dmd/Pin2DmdXl.cs
- LibDmd/Output/PinDmd1/PinDmd1.cs
- LibDmd/Output/PinDmd2/PinDmd2.cs
- LibDmd/Output/PinDmd3/PinDmd3.cs
- LibDmd/Output/PinUp/PinUpOutput.cs
- LibDmd/Output/Pixelcade/Pixelcade.cs
- LibDmd/RenderGraph.cs
Changes to fix pinup frame triggering on non colorized content.
> Funky patch

- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/Output/Virtual/Dmd/VirtualDmdControl.xaml.cs
FIxes multiple issues with alphanumeric games not gracefully handling shutdown/startup. Also improved error handling for virtual dmd frame buffer mismatches.
> Fix for alphanumeric games repeat stop/start Exception.

- Console/Mirror/MirrorOptions.cs
- LibDmd/DmdDevice/DmdDevice.cs
Fixed 128x16 games that have color content of 128x32 not applying new scaling options.  Also, attempted a fix for mirror params that would otherwise cause an exception.
> Fixed for a few additional bugs.

- PinMameDevice/PinballFX_IDs.md
- README.md
See: https://www.youtube.com/watch?v=tVy8H4v_o_I
> Add Documentation for Pinball FX.

- LibDmd/DmdDevice/AlphaNumeric.cs
> Pull out missed SmoothDigitCorners in Render2x16Alpha

- Console/Mirror/MirrorCommand.cs
- Console/Play/PlayCommand.cs
- Console/Test/TestCommand.cs
- LibDmd.Test/RenderGraph/BitmapFixedSourceTests.cs
- LibDmd.Test/RenderGraph/Gray2ConverterSourceTests.cs
- LibDmd.Test/RenderGraph/Gray2DynamicSourceTests.cs
- LibDmd.Test/RenderGraph/Gray2FixedSourceTests.cs
- LibDmd.Test/RenderGraph/Gray4ConverterSourceTests.cs
- LibDmd.Test/RenderGraph/Gray4FixedSourceTests.cs
- LibDmd.Test/RenderGraph/Gray6ConverterSourceTests.cs
- LibDmd.Test/RenderGraph/MultiDestinationTests.cs
- LibDmd.Test/RenderGraph/MultiGraphTests.cs
- LibDmd.Test/RenderGraph/Rgb24FixedSourceTests.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/Input/Network/WebsocketServer.cs
- LibDmd/RenderGraph.cs
- LibDmd/RenderGraphCollection.cs
This PR adds a reference object that keeps track of the disposable destinations, so we can make sure to dispose them once only.
> Fix multi dispose

- Console/Common/BaseOptions.cs
- LibDmd/Output/ZeDMD/ZeDMDWiFiBase.cs
- README.md
Fixes
- A typo in the CLI options
- Logic to set WIFI credentials
> Fix #490 - Setting ZeDMD WIFI credentials

- LibDmd/DmdDevice/AlphaNumeric.cs
see https://github.com/vpinball/pinmame/issues/334#issuecomment-2451545307
> Add missing clear
