- Console/Mirror/MirrorCommand.cs
- Console/Mirror/MirrorOptions.cs
- LibDmd/Common/FrameUtil.cs
- LibDmd/Input/ISource.cs
- LibDmd/Output/Virtual/VirtualDmdControl.xaml.cs
- LibDmd/RenderGraph.cs
Some refactoring was needed.
The most important change was the code connecting a source with a destination in `RenderGraph`. We now have a `Subscribe()` method that sets up the subscription and contains common code. This allowed moving the scheduler setup to `Subscribe()`, avoiding the need to set it up for every connection individually.
The `Subscribe()` method now also contains everything needed to setup the idle logic. Basically what happens when the `IdleAfter` parameter is set is that instead of subscribing to passing data to the destination, we clear dupes and then pass the data using `IObservable.Do()`. Then we throttle to the idle duration and run the idle logic in the subscription. The advantage of this approach (as opposed to using `IObservable.Timeout`) is that the original …
> Add idle animations to mirroring

- LibDmd/Input/TPAGrabber/TPAGrabber.cs
With Farsight's new cabinet support in TPA, if I rename their new binary PinballArcadeCabinet.exe to PinballArcade11.exe - dmdext works like a champ.   So this change *should* allow it to work seamlessly with cabinet mode.
> Support new TPA cabinet binary

- LibDmd/Converter/Colorize/Coloring.cs
- LibDmd/Converter/Gray2Colorizer.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/Input/PinMame/VpmGray2Source.cs
- LibDmd/Input/PinMame/VpmGray4Source.cs
Malenko is working on a TMNT colorization.    The Pin2DMD colorizations can treat 128x16 sources as centered 128x32 ones, allowing the colorization to effectively convert the machine to 128x32.   This pull request adds support for this scenario. 
Also removes some no longer used block copies.
> Support 128x16 colorizations that have scaled output to 128x32.

- LibDmd/DmdDevice/DmdDevice.cs
This is the source of the crash when dmd-ext's dmdevice.dll is used from PinballY.  
Each time PinballY switches games, it calls PM_GameSettings(), which in turn calls IDmdDevice.Init().  The implementation of DmdDevice.Init() doesn't check if it's already initialized, so it tries to re-create all of the device interfaces.  This causes a crash.
Solution is to check if the device is inited and skip the re-initialization if so.
> DmdDevice.Init: do nothing if already initialized

- LibDmd/Input/AbstractSource.cs
- LibDmd/Input/PinballFX/PinballFX3MemoryGrabber.cs
- LibDmd/Input/TPAGrabber/TPAGrabber.cs
- LibDmd/RenderGraph.cs
The current memory grabbers want you to run dmdext in Admin mode.  This shouldn't be required.  It creates all sorts of problems for users if a program imposes Admin mode as a prerequisite to run, and in this case it shouldn't be necessary.  
To use the VM_xxx permissions with OpenProcess(), you actually don't need Admin mode.  You just need the discrete privilege SeDebugPrivilege to be enabled in the process token.  Any user-mode process can debug any other user-mode process by enabling this privilege.  (A user-mode process can't debug an Admin-mode process, but users shouldn't be starting FX3 or TPA in Admin mode to start with.)
This pull request removes the Admin mode check and replaces it with enabling SeDebugPrivilege in the process token.  (It actually does still check to see if …
> remove admin mode requirement from memory grabbers; close process handles

- LibDmd/Input/PinballFX/PinballFX3MemoryGrabber.cs
- LibDmd/Input/TPAGrabber/TPAGrabber.cs
This fixes a buffer overrun in the memory grabbers that turned up in the course of removing the Admin mode requirement (see #131, #118).  
This also uses the module load size for the DMD memory block searches rather than the apparently arbitrary fixed size (0xFFFFFF) that was used in past versions.  The fixed size was insufficient in some cases (the pattern wasn't being found) and too long in other cases (it would crash the process due to ReadProcessMemory failing).  Using the actual load size seems safer in principle and in testing.  
These fixes are independent of the Admin mode pull request and should be applied even if the Admin mode pull request isn't applied.  Some of the problems in #118 actually were rooted in these issues and had nothing in fact to do with Admin mode.  The only …
> fix buffer overrun in memory grabbers

- LibDmd/DmdDevice/DmdDevice.cs
- README.md
This initializes coloring regardless whether `Init()` or `SetGameName()` is called first.
Fixes #125.
> Don't count on Init/SetGameName order when enabling coloring

- DmdExtensions.sln
Add build dependency to .sln:  ProPinballDmdSlave depends on ProPinballBridge.  You might have noticed that a clean build fails without this and has to be repeated.  The dependency fixes that and lets a clean build succeed on the first try, and will also ensure that an out-of-date copy of the dll isn't used on a partial build.
> add project dependency

- LibDmd/Input/MemoryGrabber.cs
- LibDmd/Input/MemoryGrabberBase.cs
- LibDmd/Input/PinballFX/PinballFX3MemoryGrabber.cs
- LibDmd/Input/TPAGrabber/TPAGrabber.cs
- LibDmd/LibDmd.csproj
This refactors the TPA and FX3 memory grabbers so that they use a common base class, per my suggestion in #133.  I moved as much of the generic code as possible into the base class, so the individual grabbers are pretty well stripped down to just the target-specific operations to hack into the subject process memory.  The basic grabber mechanism is all in common code now.  I think this will make the grabbers more maintainable in the future, and will also make it a lot easier to write new grabbers that become interesting.
I also cleaned up the muddle about pointers vs offsets, and fixed all of the dllimport signatures to match the actual DLL exports.  That's a hard requirement for x64, because 'int' and 'IntPtr' are different sizes in that context, but it also cleans up a bunch of …
> Memory grabber refactor

- .editorconfig
- Console/DmdExt.cs
- DmdExtensions.sln
- LibDmd/Common/CultureUtil.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/LibDmd.csproj
- README.md
@freezy This pull request should fix the language culture setting issues discussed here:
https://github.com/freezy/dmd-extensions/issues/154
Additionally I added a .editorconfig so that my visual studio settings don't interfere with your visual studio settings as I know you want the standard to be tabs in .cs files :-)
Lastly, i updated notes in the config file that version 1.8 users (which I am assuming is what you are going to version the next release as?) that they should update the DMDDevice.ini if they did make customizations to it and are under a language that represents decimals with a comma instead of a period (I only know of German that does that but there are others i'm sure).
Also, I ran into an issue with Fody on a fresh checkout, turns out it's some sort of wierd visual …
> culture fix

- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/Output/Network/BrowserStream.cs
Add game name (rom) on init request to the browser stream, to allow the requester to adapt its rendering to the game.
The browser stream output allow to create fancy DMD rendering. To allow skinning based on the game rom, you need to get this information from PinMame. The most clean way is for dmdext to pull it on init request, hence this small pull request. This allows little software like [DMDOverlay](https://vpinball.com/VPBdownloads/dmd-overlay/) to be more clean and simple.
> Add game name to browser stream

- LibDmd/Common/ImageUtil.cs
- LibDmd/Input/PinballFX/PinballFXGrabber.cs
- README.md
This implements the changes discussed in #205. This results in really crisp output for FX3.  Unfortunately I don't have FX2 and it doesn't seem to be available for download anymore.  It would be really nice if someone could test it out and LMK if this is a good change for FX2 or if I should refactor to make these changes only apply to FX3.
> Pixel Grabber Tweaks for FX3

- LibDmd/DmdDevice/DmdDevice.cs
When using FlexDMD with TNA table I observed that dmd-extensions didn't know where to put the DMD.  The log shows it trying to get the position from the root VPM dir. because _gamename is empty.   We should use the VPM default key when we can't find the position.
> Use VPM "default" key for position when entry not found

- Console/Common/BaseCommand.cs
- Console/Common/BaseOptions.cs
- LibDmd/Common/FrameUtil.cs
- LibDmd/Common/ImageUtil.cs
- LibDmd/DmdDevice/Configuration.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/DmdDevice/IConfiguration.cs
- LibDmd/LibDmd.csproj
- LibDmd/Output/PinDmd3/PinDmd3.cs
- LibDmd/Output/Pixelcade/Pixelcade.cs
- PinMameDevice/DmdDevice.ini
- README.md
This is a first implementation of the [Pixelcade](http://pixelcade.org/) RGB display. It currently addresses the device through the serial port directly.
Roughly here's what the driver's doing:
1. Loop through serial ports, connect and read bytes.
2. If bytes were read, first byte starts with `0x0`, followed by "IOIO" and 24 bytes of hardware, bootloader and firmware info, we're good to go.
3. In this case, enable "streaming mode" by sending `0x1e` and another computed byte
4. On incoming frame, convert to RGB planes, and send `0x1f` plus the data
I might have misunderstood the above from reading a lot of code of the [Java implementation](https://github.com/alinke/PIXEL). Please @alinke or @ytai feel free to chime in.
> Add support for Pixelcade displays

- LibDmd/Output/PinDmd3/PinDmd3.cs
> PinDMD3: Add support for colored 4-bit

- Console/Common/BaseCommand.cs
- Console/Common/BaseOptions.cs
- LibDmd/DmdDevice/Configuration.cs
- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/DmdDevice/IConfiguration.cs
- LibDmd/Output/Network/NetworkStream.cs
- PinMameDevice/DmdDevice.ini
Found that if the WebSocket service side of this was not already started or had to be restarted during a run, the WebSocket client wouldn't recover so no DMD updates would be sent.
This change is one approach at allowing the connection to recover if the service is not already running when a game starts or gets restarted during the lifetime of a game run.
Tested using both the dmdext cli tool and via VPX game setup that uses the network streaming option.
Retry feature is disabled by default and when enabled, a retry interval of 5 seconds. The retry interval can be changed via another option to be more or less frequent, lowest interval is 1 second.
> Add basic support for Websocket connection retry

- LibDmd/LibDmd.csproj
Fix missing native lib for x64 (see https://github.com/freezy/dmd-extensions/issues/212). The dll given to Costura is the one taken from the LibSkiaSharp nuget package (like for x86). Note that I only did limited testing on this PR. Please check before merging !
> Fix missing Skia native lib

- LibDmd/Common/ColorUtil.cs
This is small fix for the crash reported here: https://www.vpforums.org/index.php?showtopic=45797
It is not really a Freezy's DMD bug, but more a VPinMame one, but Freezy's DMD should not crash even when fed with incorrect data (here, VPM sends out of palette data for Pirate of The Caraibs during extraball sequence, or for World Poker Tour).
Here is a crash report of such a situation (others can be found on VPForum):  
[9] 2020/08/17 23:24:37.352  INFO | Successfully loaded config from C:\Visual Pinball\VPinMAME\DmdDevice.ini. 
[9] 2020/08/17 23:24:37.466  INFO | No altcolor folder found, ignoring palettes. 
[9] 2020/08/17 23:24:37.475  INFO | Starting VPinMAME API 1.8.1-SNAPSHOT through VPinballX.exe. 
[9] 2020/08/17 23:24:37.475  INFO | Assembly located at C:\Visual …
> Fix Crash when VPM sends data out of the palette range

- LibDmd/DmdDevice/DmdDevice.cs
- PinMameDevice/DmdDevice.cs
The initial PR was made a bit too fast: this PR fixes the bad cpy/paste that lead to using the incorrect device for some calls. 
It also fixes the use of Hide instead of Close for WPF windows which does not release the underlying window.
> Multiple instance fix

- LibDmd/DmdDevice/DmdDevice.cs
- LibDmd/RenderGraph.cs
This PR change the way the frames are dispatched to the destination ; instead of processing each frame the one after the other, it will process only the latest unprocessed frame, dropping any frame that may have been received while processing.
This change is needed to avoid a situation where the pinball controller process frames at a higher rate that the device can process. In this situation, the frames stack up and little by little, the display lags behind the controller. There has been a few post on VPForum on this or issue reports ([latest from Thalamus](https://www.vpforums.org/index.php?showtopic=43569&p=472062) that made me work on this).
I do not have hardware DMD but Thalamus did the testing and report that it improves (see [here](https://github.com/vbousquet/flexdmd/issues/21)). …
> Drop missed frames instead of trying to catch up

- LibDmd/Input/FutureDmd/FutureDmdSink.cs
-  Rearranged the calls to the pipe server
- Added to the condition for when a message has been completed
- Added functionality to convert message to frame data
- Added a thread sleep to each processing of a frame or 99% of a CPU core would be used
- Added 3 helper methods: ConvertMessage , GetEmptyMessage and GetByteFromHexCharValue
> First check-in of the Future Pinball Sink

- LibDmd/LibDmd.csproj
- LibDmd/Output/Virtual/Dmd/OpenGLControlExt.xaml
- LibDmd/Output/Virtual/Dmd/OpenGLControlExt.xaml.cs
- LibDmd/Output/Virtual/Dmd/VirtualDmdControl.xaml
- LibDmd/Output/Virtual/Dmd/VirtualDmdControl.xaml.cs
This PR contains the change discussed in issue https://github.com/freezy/dmd-extensions/issues/283
There were 2 problems:
- SharpGL implementation performs rendering in a FBO, then copy the FBO to the native window. This copy was somewhat inefficient, and the code did trigger a GC at each copy leading to poor performance. This is discussed here https://github.com/dwmkerr/sharpgl/commit/c436feff10ac0078cbf9bca44c642c80d0ece1f4 and here https://github.com/dwmkerr/sharpgl/pull/145.
- The other issue is that the implementation used a fixed rendering loop (timer based at a fixed framerate). The rendering frequency was not the one of the DMD source, leading to animation stuttering. This was not a performance problem but gave bad smoothness and lead to a perceptions of stutter and a feeling of a …
> Stutter fix

- LibDmd/Output/PinUp/PinUpOutput.cs
This is a tiny PR to use the right pup dll according to the architecture (PuP x64 is not yet released but should be soon).
> Add support for dmddevicePUP64.dll

- Console/Common/BaseCommand.cs
- Console/Mirror/MirrorCommand.cs
- LibDmd/Output/Virtual/Dmd/VirtualDmdControl.xaml.cs
Fixes #357
Allows unlocked AR for virtual DMD when using the mirror command again.
> Fixes screen grab crash

- LibDmd/DmdDevice/Configuration.cs
- LibDmd/Output/Virtual/AlphaNumeric/AlphaNumericSettings.xaml
- LibDmd/Output/Virtual/AlphaNumeric/AlphaNumericSettings.xaml.cs
- LibDmd/Output/Virtual/AlphaNumeric/AlphanumericControl.xaml.cs
- LibDmd/Output/Virtual/AlphaNumeric/DisplaySetting.cs
- LibDmd/Output/Virtual/AlphaNumeric/RasterizeDimensions.cs
- LibDmd/Output/Virtual/AlphaNumeric/RasterizeStyle.cs
Changed Outer Padding and Line Padding for Alphanumeric Displays to use value from DMDDevice.ini
> Alphanumeric Padding

- LibDmd/Output/ZeDMD/ZeDMDBase.cs
closes https://github.com/freezy/dmd-extensions/issues/474
> Close serial connection for ZeDMD on Dispose(),

- LibDmd/DmdDevice/DmdDevice.cs
- PinMameDevice/DmdDevice.cs
This PR actually applies `Set_4_Colors_Palette_Device()` and `Set_16_Colors_Palette_Device()` to the render graph and not just as an initialization value.
This is so Zen Studios can use this API for their palette changes without having to re-initialize the entire stack, which currently leads to frame stutters.
> fix: Apply host palette changes to rendergraph.

- .github/workflows/build.yml
- Add automated build for x86 and x64 with GitHub Actions
- Generate MSI package for both platforms
- Publish a GitHub release when there is a tag from master/main
This PR replaces #493
> Add automated builds with GitHub actions

- LibDmd/Converter/ColorizationLoader.cs
DMDext checks for a cRZ file only to start a Serum colorization. But libdmdutil also loads uncompressed cROM files.
So DMDext should accept these as well.
> Support Serum cROM and cROMc files
